In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam (1).csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam'] = df["Category"].apply(lambda x:1 if x =='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.20)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_CV = v.fit_transform(X_train.values)
X_train_CV

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59023 stored elements and shape (4457, 7664)>

In [19]:
X_train_CV.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
X_train_CV.shape

(4457, 7664)

In [21]:
v.get_feature_names_out()[6847]

'titles'

In [22]:
v.vocabulary_

{'but': 1570,
 'really': 5549,
 'broke': 1517,
 'oh': 4856,
 'no': 4744,
 'amount': 949,
 'is': 3714,
 'too': 6905,
 'small': 6175,
 'even': 2638,
 'lt': 4214,
 'gt': 3231,
 'cant': 1637,
 'pick': 5152,
 'the': 6741,
 'phone': 5140,
 'right': 5721,
 'now': 4786,
 'pls': 5210,
 'send': 5943,
 'message': 4404,
 'not': 4776,
 'able': 755,
 'to': 6865,
 'sleep': 6151,
 'can': 1625,
 'win': 7444,
 '100': 251,
 'of': 4836,
 'music': 4600,
 'gift': 3107,
 'vouchers': 7256,
 'every': 2645,
 'week': 7363,
 'starting': 6381,
 'txt': 7028,
 'word': 7513,
 'draw': 2422,
 '87066': 691,
 'tscs': 6997,
 'www': 7561,
 'idew': 3560,
 'com': 1891,
 'skillgame': 6137,
 '1winaweek': 335,
 'age16': 862,
 '150ppermesssubscription': 302,
 'dear': 2174,
 'good': 3160,
 'morning': 4535,
 'only': 4892,
 'am': 934,
 'up': 7115,
 'waiting': 7282,
 'for': 2913,
 'your': 7632,
 'call': 1602,
 'think': 6774,
 'might': 4421,
 'have': 3326,
 'give': 3119,
 'it': 3726,
 'miss': 4459,
 'teaching': 6662,
 'til': 6827,
 '

In [24]:
X_train_np = X_train_CV.toarray()
X_train_np[:4]
np.where(X_train_np[0]!= 0)

(array([ 949, 1517, 1570, 2638, 3231, 3714, 4214, 4744, 4856, 5549, 6175,
        6905], dtype=int64),)

In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [26]:
model.fit(X_train_CV,y_train)

MultinomialNB()

In [31]:
X_test_CV = v.transform(X_test)

In [32]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_CV)
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       963\n           1       0.99      0.91      0.95       152\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.95      0.97      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [33]:
emails = ['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
          'Yeah do! Don‘t stand to close tho- you‘ll catch something!']
emails_count = v.transform(emails)
model.predict(emails_count)

array([0], dtype=int64)

In [34]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [35]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       963
           1       0.99      0.91      0.95       152

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

